

export const products = [
  {
    id: 1,
    title: "Golden Soft",
    description: "Вариативный замок Golden Soft для отеля",
    price: 7_000,

    discountPercentage: '❌ Нет в наличии',
    rating: 4.69,
    stock: 8_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XYKFhdmc/img-1.png",
    images: [
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
    ],
  },
  {
    id: 2,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 33_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 39_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XqMdmLjL/img-2.png",
    images: [
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
    ],
  },
  {
    id: 3,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 9_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 12_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/wvzskv04/img-3.png",
    images: [
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
    ],
  },
  {
    id: 4,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 9_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 12_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/wvzskv04/img-3.png",
    images: [
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
    ],
  },
  {
    id: 5,
    title: "Golden Soft",
    description: "Вариативный замок Golden Soft для отеля",
    price: 7_000,
    discountPercentage: '❌ Нет в наличии',
    rating: 4.69,
    stock: 8_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XYKFhdmc/img-1.png",
    images: [
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
    ],
  },
  {
    id: 6,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 33_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 39_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XqMdmLjL/img-2.png",
    images: [
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
    ],
  },
  {
    id: 7,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 9_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 12_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/wvzskv04/img-3.png",
    images: [
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
    ],
  },
  {
    id: 8,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 33_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 39_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XqMdmLjL/img-2.png",
    images: [
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
    ],
  },
  {
    id: 9,
    title: "Golden Soft",
    description: "Вариативный замок Golden Soft для отеля",
    price: 7_000,
    discountPercentage: '❌ Нет в наличии',
    rating: 4.69,
    stock: 8_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XYKFhdmc/img-1.png",
    images: [
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
    ],
  },
  {
    id: 10,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 33_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 39_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XqMdmLjL/img-2.png",
    images: [
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
      "https://i.postimg.cc/XqMdmLjL/img-2.png",
    ],
  },
  {
    id: 11,
    title: "Golden Soft",
    description: "Дверной Замок Golden Soft для офиса",
    price: 9_000,
    discountPercentage: '✅ В наличии',
    rating: 4.69,
    stock: 12_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/wvzskv04/img-3.png",
    images: [
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
      "https://i.postimg.cc/wvzskv04/img-3.png",
    ],
  },
  {
    id: 12,
    title: "Golden Soft",
    description: "Вариативный замок Golden Soft для отеля",
    price: 7_000,
    discountPercentage:'❌ Нет в наличии',
    rating: 4.69,
    stock: 8_000,
    brand: "Golden Soft",
    category: "замок",
    thumbnail: "https://i.postimg.cc/XYKFhdmc/img-1.png",
    images: [
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
      "https://i.postimg.cc/XYKFhdmc/img-1.png",
    ],
  },
];
